# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

# Load .env file of workspace
dotenv: [ ".env" ]

# Echo off
silent: true

vars:
  workspace_dir: "{{.ROOT_DIR}}"
  ti_gmake_dir: "{{.ENV_CCS_INSTALL_DIR}}/utils/bin"
  
  ti_openocd_bin_dir: "{{.ROOT_DIR}}/{{.ENV_OPENOCD_REL_DIR}}/bin"
  ti_openocd_script_dir: "{{.ROOT_DIR}}/{{.ENV_OPENOCD_REL_DIR}}/share/openocd/scripts"

  ti_ccs_script_launcher: "{{.ENV_CCS_INSTALL_DIR}}/scripting/python/launcher.py"

tasks:
  util_code_line_count:
    desc: "Count code lines"
    cmds:
    - echo "=================================================="
    - echo "Count Code Lines of Project"
    - echo "=================================================="    
    - >
      tool/cli/scc ./ccs_project/src

  util_port_list:
    desc: "List serial port"
    cmds:
    - echo "=================================================="
    - echo "List Serial Port"
    - echo "=================================================="
    - >
      tool/cli/lser.exe

  ccs_build_project:
    desc: "Build project"
    dir: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}"
    cmds:
    - echo "=================================================="
    - echo "Build Project"
    - echo "=================================================="
    - >
      {{.ti_gmake_dir}}/gmake.exe -s -k -j 24 all -r -O

  ccs_clean_project:
    desc: "Clean project"
    dir: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}"
    cmds:
    - echo "=================================================="
    - echo "Clean Project"
    - echo "=================================================="
    - >
      {{.ti_gmake_dir}}/gmake.exe -s -k -j 24 clean -r -O

  ccs_rebuild_project:
    desc: "Rebuild project"
    dir: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}"
    deps: [ccs_clean_project, ccs_build_project]
    cmds:
    - echo "=================================================="
    - echo "Rebuild Project"
    - echo "=================================================="

  ccscript_read_hsm_ver:
    desc: "Read HSM version"
    cmds:
    - echo "=================================================="
    - echo "Read HSM Version"
    - echo "=================================================="
    - >
      py {{.ti_ccs_script_launcher}} ./script/ccs/read_hsm_version.py

  ccscript_check_blank:
    desc: "Check blank"
    cmds:
    - echo "=================================================="
    - echo "Check blank"
    - echo "=================================================="
    - >
      py {{.ti_ccs_script_launcher}} ./script/ccs/check_blank.py

  ccscript_program_hsm:
    desc: "Program HSM"
    cmds:
    - echo "=================================================="
    - echo "Program HSM"
    - echo "=================================================="
    - >
      py {{.ti_ccs_script_launcher}} ./script/ccs/program_hsm.py

  ccscript_program_app:
    desc: "Program Application"
    cmds:
    - echo "=================================================="
    - echo "Program Application"
    - echo "=================================================="
    - >
      py {{.ti_ccs_script_launcher}} ./script/ccs/program_hex.py

  # ccscript_TEST:
  #   desc: "Erase Application(keep HSM unchanged)"
  #   cmds:
  #   - echo "=================================================="
  #   - echo "Erase Application(keep HSM unchanged)"
  #   - echo "=================================================="
  #   - >
  #     py {{.ti_ccs_script_launcher}} ./script/ccs/test.py

  ccscript_erase_chip:
    desc: "Erase Application and HSM"
    cmds:
    - echo "=================================================="
    - echo "Erase Application and HSM"
    - echo "=================================================="
    - >
      py {{.ti_ccs_script_launcher}} ./script/ccs/erase_chip.py

  ccscript_soft_reset:
    desc: "Soft Reset"
    cmds:
    - echo "=================================================="
    - echo "Soft Reset"
    - echo "=================================================="
    - >
      py {{.ti_ccs_script_launcher}} ./script/ccs/soft_reset.py

  xds110_pin_reset:
    desc: "Reset Device(Pin Reset)"
    cmds:
    - echo "=================================================="
    - echo "Reset Device(Pin Reset)"
    - echo "=================================================="
    - >
      py {{.ti_ccs_script_launcher}} ./script/ccs/pin_reset.py

  # openocd_program_app:
  #   desc: "Program device"
  #   vars:
  #     binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_OUT_FILE}}"
  #   cmds:
  #   - echo "=================================================="
  #   - echo "Program Device"
  #   - echo "=================================================="
  #   - echo "{{.cmd_str}}"
  #   - >
  #     {{.ti_openocd_bin_dir}}/openocd.exe 
  #     -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
  #     -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg 
  #     -c "init; halt; program {{.binary_file_path}}; reset; exit;"

  # openocd_soft_reset:
  #   desc: "Reset Device(Soft Reset)"
  #   vars:
  #     binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_OUT_FILE}}"
  #   cmds:
  #   - echo "=================================================="
  #   - echo "Reset Device(Soft Reset)"
  #   - echo "=================================================="
  #   # Command: bin/openocd.exe -f share/openocd/scripts/interface/xds110.cfg -f share/openocd/scripts/board/ti_lp_em_cc2745r10.cfg  -c "init; reset init; reset run; exit"
  #   # Don't know why it is this, but it works
  #   - >
  #     {{.ti_openocd_bin_dir}}/openocd.exe 
  #     -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
  #     -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg 
  #     -c "init; reset init; reset run; exit"

  # openocd_start_server:
  #   desc: "Start OpenOCD Server"
  #   vars:
  #     binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_OUT_FILE}}"
  #   cmds:
  #   - echo "=================================================="
  #   - echo "Start OpenOCD Server"
  #   - echo "=================================================="
  #   # Command: bin/openocd.exe -f share/openocd/scripts/interface/xds110.cfg -f share/openocd/scripts/board/ti_lp_em_cc2745r10.cfg
  #   # Then user can use Telnet at: localhost:4444 and GDB at: localhost:3333
  #   - >
  #     {{.ti_openocd_bin_dir}}/openocd.exe 
  #     -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
  #     -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg

  # openocd_start_itm:
  #   desc: "Start OpenOCD ITM"
  #   vars:
  #     binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_OUT_FILE}}"
  #   cmds:
  #   - echo "=================================================="
  #   - echo "Start OpenOCD ITM"
  #   - echo "=================================================="
  #   # Command: bin/openocd.exe -f share/openocd/scripts/interface/xds110.cfg -f share/openocd/scripts/board/ti_lp_em_cc2745r10.cfg -c "itm port 0"
  #   - >
  #     {{.ti_openocd_bin_dir}}/openocd.exe 
  #     -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
  #     -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg
