# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

# Load .env file of workspace
dotenv: [ ".env" ]

# Echo off
silent: true

vars:
  workspace_dir: "{{.ROOT_DIR}}"
  ti_gmake_dir: "{{.ENV_CCS_INSTALL_DIR}}/ccs/utils/bin"
  
  ti_openocd_bin_dir: "{{.ROOT_DIR}}/{{.ENV_OPENOCD_REL_DIR}}/bin"
  ti_openocd_script_dir: "{{.ROOT_DIR}}/{{.ENV_OPENOCD_REL_DIR}}/share/openocd/scripts"

tasks:
  code_line_count:
    desc: "Count code lines"
    cmds:
    - echo "=================================================="
    - echo "Count Code Lines of Project"
    - echo "=================================================="    
    - >
      tool/cli/scc ./ccs_project/src

  list_port:
    desc: "List serial port"
    cmds:
    - echo "=================================================="
    - echo "List Serial Port"
    - echo "=================================================="
    - >
      tool/cli/lser.exe

  ccs_build_project:
    desc: "Build project"
    dir: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}"
    cmds:
    - echo "=================================================="
    - echo "Build Project"
    - echo "=================================================="
    - >
      {{.ti_gmake_dir}}/gmake.exe -s -k -j 24 all -r -O

  ccs_clean_project:
    desc: "Clean project"
    dir: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}"
    cmds:
    - echo "=================================================="
    - echo "Clean Project"
    - echo "=================================================="
    - >
      {{.ti_gmake_dir}}/gmake.exe -s -k -j 24 clean -r -O

  ccs_rebuild_project:
    desc: "Rebuild project"
    dir: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}"
    deps: [ccs_clean_project, ccs_build_project]
    cmds:
    - echo "=================================================="
    - echo "Rebuild Project"
    - echo "=================================================="

  openocd_program:
    desc: "Program device"
    vars:
      binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_HEX_NAME}}.out"
    cmds:
    - echo "=================================================="
    - echo "Program Device"
    - echo "=================================================="
    - echo "{{.cmd_str}}"
    - >
      {{.ti_openocd_bin_dir}}/openocd.exe 
      -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
      -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg 
      -c "init; halt; program {{.binary_file_path}}; reset; exit;"

  openocd_erase:
    desc: "Erase Device"
    vars:
      binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_HEX_NAME}}.out"
    cmds:
    - echo "=================================================="
    - echo "Erase Device"
    - echo "=================================================="
    # Command: bin/openocd.exe -f share/openocd/scripts/interface/xds110.cfg -f share/openocd/scripts/board/ti_lp_em_cc2745r10.cfg  -c "init; halt; program xxx.out; [verify;] reset; exit"
    - >
      {{.ti_openocd_bin_dir}}/openocd.exe 
      -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
      -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg 
      -c "init; halt; program {{.binary_file_path}}; reset; exit;"

  openocd_reset:
    desc: "Reset Device"
    vars:
      binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_HEX_NAME}}.out"
    cmds:
    - echo "=================================================="
    - echo "Reset Device"
    - echo "=================================================="
    # Command: bin/openocd.exe -f share/openocd/scripts/interface/xds110.cfg -f share/openocd/scripts/board/ti_lp_em_cc2745r10.cfg  -c "init; reset init; reset run; exit"
    # Don't know why it is this, but it works
    - >
      {{.ti_openocd_bin_dir}}/openocd.exe 
      -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
      -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg 
      -c "init; reset init; reset run; exit"

  openocd_start_server:
    desc: "Start OpenOCD Server"
    vars:
      binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_HEX_NAME}}.out"
    cmds:
    - echo "=================================================="
    - echo "Start OpenOCD Server"
    - echo "=================================================="
    # Command: bin/openocd.exe -f share/openocd/scripts/interface/xds110.cfg -f share/openocd/scripts/board/ti_lp_em_cc2745r10.cfg
    # Then user can use Telnet at: localhost:4444 and GDB at: localhost:3333
    - >
      {{.ti_openocd_bin_dir}}/openocd.exe 
      -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
      -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg

  # openocd_start_itm:
  #   desc: "Start OpenOCD ITM"
  #   vars:
  #     binary_file_path: "{{.workspace_dir}}/ccs_project/{{.ENV_CCS_BUILD_TARGET}}/{{.ENV_PROJECT_HEX_NAME}}.out"
  #   cmds:
  #   - echo "=================================================="
  #   - echo "Start OpenOCD ITM"
  #   - echo "=================================================="
  #   # Command: bin/openocd.exe -f share/openocd/scripts/interface/xds110.cfg -f share/openocd/scripts/board/ti_lp_em_cc2745r10.cfg -c "itm port 0"
  #   - >
  #     {{.ti_openocd_bin_dir}}/openocd.exe 
  #     -f {{.ti_openocd_script_dir}}/interface/xds110.cfg 
  #     -f {{.ti_openocd_script_dir}}/board/ti_lp_em_cc2745r10.cfg
