#ifndef BLE_SCAN_PARAM_H
#define BLE_SCAN_PARAM_H

#include "ti_ble_config.h"

#if (HOST_CONFIG & CENTRAL_CFG)

#define BLE_PARAM_INITIATOR_PHY      DEFAULT_INIT_PHY
#define BLE_PARAM_CONN_SCAN_INTERVAL INIT_PHYPARAM_SCAN_INT
#define BLE_PARAM_CONN_SCAN_WINDOW   INIT_PHYPARAM_SCAN_WIN
#define BLE_PARAM_CONN_INTERVAL_MIN  INIT_PHYPARAM_MIN_CONN_INT
#define BLE_PARAM_CONN_INTERVAL_MAX  INIT_PHYPARAM_MAX_CONN_INT
#define BLE_PARAM_SLAVE_LATENCY      INIT_PHYPARAM_CONN_LAT
#define BLE_PARAM_SUP_TIMEOUT        INIT_PHYPARAM_SUP_TO

#define BLE_PARAM_SCAN_PRIMARY_PHY  DEFAULT_SCAN_PHY
#define BLE_PARAM_SCAN_TYPE         DEFAULT_SCAN_TYPE
#define BLE_PARAM_SCAN_INTERVAL     DEFAULT_SCAN_INTERVAL
#define BLE_PARAM_SCAN_WINDOW       DEFAULT_SCAN_WINDOW
#define BLE_PARAM_ADV_REPORT_FIELDS ADV_RPT_FIELDS
#define BLE_PARAM_SCAN_PHYS         DEFAULT_INIT_PHY
#define BLE_PARAM_FILTER_POLICY     SCANNER_FILTER_POLICY
#define BLE_PARAM_FILTER_PDU_TYPE   SCANNER_FILTER_PDU_TYPE
#define BLE_PARAM_FILTER_MIN_RSSI   SCANNER_FILTER_MIN_RSSI
#define BLE_PARAM_FILTER_DISC_MODE  SCANNER_FILTER_DISC_MODE
#define BLE_PARAM_DUPLICATE_FILTER  SCANNER_DUPLICATE_FILTER

#else

#define BLE_PARAM_INITIATOR_PHY      0
#define BLE_PARAM_CONN_SCAN_INTERVAL 0
#define BLE_PARAM_CONN_SCAN_WINDOW   0
#define BLE_PARAM_CONN_INTERVAL_MIN  0
#define BLE_PARAM_CONN_INTERVAL_MAX  0
#define BLE_PARAM_SLAVE_LATENCY      0
#define BLE_PARAM_SUP_TIMEOUT        0

#define BLE_PARAM_SCAN_PRIMARY_PHY  0
#define BLE_PARAM_SCAN_TYPE         0
#define BLE_PARAM_SCAN_INTERVAL     0
#define BLE_PARAM_SCAN_WINDOW       0
#define BLE_PARAM_ADV_REPORT_FIELDS 0
#define BLE_PARAM_SCAN_PHYS         0
#define BLE_PARAM_FILTER_POLICY     0
#define BLE_PARAM_FILTER_PDU_TYPE   0
#define BLE_PARAM_FILTER_MIN_RSSI   0
#define BLE_PARAM_FILTER_DISC_MODE  0
#define BLE_PARAM_DUPLICATE_FILTER  0

#endif

#endif
